# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WebAppContainers-GovChatNL-weu-PilotAI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_08b0824fa2c04f388a3905be670e7d5e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b05a5976a09546ba860c482504598e8b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_08b0824fa2c04f388a3905be670e7d5e }}/govchat-nl:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebAppContainers-GovChatNL-weu-PilotAI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c83c14064c94623999fb7ee93a80d81 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_08b0824fa2c04f388a3905be670e7d5e }}/govchat-nl:${{ github.sha }}'